### ISSUE TITLE
Icon List: The icon does not appear when using Icon List on I.E

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#127]
**Describe the bug**
When using the Icon List the icon does not appear on Back End and Front End when using I.E

**To Reproduce**
1. Add a new page
2. Create Icon List
3. Publish the page
4. Check on Front End

**Expected behavior**
A simple bullet should appear when using the Icon List.

**Screenshots**
Back End
![image](https://user-images.githubusercontent.com/51441886/59740303-444c9800-929a-11e9-8083-039d14a5c534.png)

Front End
![image](https://user-images.githubusercontent.com/51441886/59740322-53334a80-929a-11e9-9b22-8c98e6ed3243.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE 11

**Comment by yssagambit** [comment]
`@media all and (-ms-high-contrast:none) {
	*::-ms-backdrop, .ugb-icon-list li {
		list-style: inside disc !important
	}
*::-ms-backdrop, .ugb-icon-list li:before {
		content: none !important
	}
}`

**Comment by yssagambit** [comment]
Here's the CSS Code that fixes this issue:

```CSS
@media all and (-ms-high-contrast:none) {
	*::-ms-backdrop, .ugb-icon-list li {
		list-style: inside disc !important
	}
*::-ms-backdrop, .ugb-icon-list li:before {
		content: none !important
	}
}
```
