### ISSUE TITLE
Column block has unwanted margin bottom

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1937]
1. Add a Columns block, pick 2-columns
2. Add an Image block on the first column
3. Remove the Style tab > Spacing in the Column Block
4. Remove the Block tab > Paddings in the Columns Block
5. Preview, see the margin bottom on the Column Block.

https://user-images.githubusercontent.com/1033611/137734198-2603c955-35b1-41bc-93a5-48c34b65aafa.mp4

Fix: add
```css
.stk-block-column__content > .stk-inner-blocks {
    margin-bottom: 0;
}
```
