### ISSUE TITLE
on edge, the block and column spacing options (in the inspector) are broken

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#260]
**Describe the bug**
on edge, the block and column spacing options (in the inspector) are broken

![image](https://user-images.githubusercontent.com/51441886/66113293-1435c480-e5ff-11e9-8276-ef2642223a67.png)

![image](https://user-images.githubusercontent.com/51441886/66113318-20218680-e5ff-11e9-9ed2-40ef744bb1c9.png)

**Comment by yssagambit** [comment]
```css
.ugb-four-range-control__range .components-range-control {
    flex: 1;
}
```

Also fixes: #259
