### ISSUE TITLE
Carousel block: visible horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by owlnical** [gambitph/Stackable#2701]
**Describe the bug**

Carousel block. A horizontal scrollbar is visible in Firefox.

**To Reproduce**

1. Add a carousel block in Firefox

**Expected behavior**

The scrollbar should be optional and not visible by default.

**Screenshots**

![image](https://github.com/gambitph/Stackable/assets/5972188/3978b18d-b9f1-4128-8888-a0c897e0b730)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Firefox (clean profile no add-ons)
 - Browser Version: 114.0.1 (64-bit)
 - Stackable: Version 3.9.0 

**Workaround in frontend_blocks.css**

`-moz-scrollbars-none;` is an invalid property value according to the dev tools. I replaced it with `hidden`, which works.

````css
.stk-block-carousel.stk--is-slide .stk-block-carousel__slider {
...
 /* overflow-x:-moz-scrollbars-none; */
 overflow-x: hidden;
...
}
````
