### ISSUE TITLE
[Firefox] 1-column has spacing when viewed in Firefox

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#2862]
This style in `src/styles/block-design-system-blocks.scss`

```css
body:not(.wp-admin) .stk-block-columns:has(> .stk-block-content > .stk-block-column:first-child:last-child) { // Remove the margins if it's only 1 block.
	--stk-columns-spacing: 0;
}
```

doesn't work in Firefox, so a Columns block with only 1 Inner Column block incorrectly gets some spacing.
