### ISSUE TITLE
Background image overlay does not work for notification elements

### ISSUE THREAD

**Issue by timlg07** [gambitph/Stackable#2959]
**Describe the bug**
For notification elements setting the Background Media Tint has an effect only in the editor, not in the frontend. The `stk--has-background-overlay` class is missing.  
If I manually add the class in the browsers inspector, it works as expected. Other elements (like columns) do still get the `stk--has-background-overlay` class.

**To Reproduce**
1. Create a new notification block
2. Go to the block settings > Style > Container Background
3. Set a Background Color, Background Image & Background Media Tint
4. Save page or open preview
5. See error (image is not tinted, `.stk--has-background-overlay` is missing)

**Expected behavior**
The notification element should have the `stk--has-background-overlay` class creating the ::before element that tints its background.

**Screenshots**
<table><tr><td><img width="1313" alt="editor" src="https://github.com/gambitph/Stackable/assets/33633786/31a7a453-e640-4f6e-a9e5-f65cca0fcfea"></td><td>
<img width="889" alt="frontend" src="https://github.com/gambitph/Stackable/assets/33633786/64cfac1f-87ef-4764-96a5-b6253f0ba220"></td></tr></table>

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 119

**Additional Info**  
For old pages with notifications the overlay still works. As long as you don't open them and save them again.

**Comment by timlg07** [comment]
**Temporary fix:**   
Because I have background tint on all notifications, I just added the following CSS to my child theme:

```css
.stk-block-notification__content::before {
	bottom: 0;
	content: ""!important;
	left: 0;
	position: absolute;
	right: 0;
	top: 0;
	z-index: 2;
}
.stk-block-notification__content>* {
	position: relative;
	z-index: 3;
}
```
