### ISSUE TITLE
Container background image size

### ISSUE THREAD

**Issue by iDevelopper** [gambitph/Stackable#59]
Hi there,

I would like a container block with a background image that scale to fit the container.

An option to scale the content to fit the size of the container by maintaining the aspect ratio. Any remaining area of the container’s bounds will be transparent.

I did not find this option.

Any help please?

**Comment by bfintal** [comment]
Hi, we didn't add the other values for `background-size` to make things simpler.

However, you can just add a custom class to your container block, then put some additional css to make the background image to contain:

```css
.my-container {
    background-size: contain;
    background-color: transparent;
}
```
