### ISSUE TITLE
When you lower the Image Column Width it will not look good on Tablet

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#598]
Steps:
1. Add a Feature Block
2. Change the Image Column Width
3. Preview on Tablet

![image](https://user-images.githubusercontent.com/51441886/74823306-79394f00-5341-11ea-91dd-718880f898b3.png)

We gave CSS code to the customer to fix this:

```CSS
@media screen and (min-width: 768px) {
.ugb-feature.ugb-feature .ugb-feature__item {
    grid-template-columns: 1fr !important;
}
}
```
