### ISSUE TITLE
Theme anchor styles affect button styles

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#599]
If you have this in your Customizer > Additional CSS:

```css
.entry-content div a, .entry-content div a:hover {
    border-bottom: none;
    padding-bottom: 0;
}

.comment-reply-link, .comment-respond a, .entry-content a, .footer-bottom .herald-copyright a {
    padding-bottom: 2px;
    border-bottom: 2px solid transparent;
    transition: border-bottom .15s ease-in;
}
```

Ghost buttons (and possibly other styles) would have their bottom borders cut, and their paddings change on mouse over.

Content:
```html
<!-- wp:ugb/button {"button1Design":"ghost","uniqueClass":"ugb-8b332f6"} -->
<div class="wp-block-ugb-button ugb-button-wrapper ugb-8b332f6 ugb-main-block" id=""><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-button-container"><a class="ugb-button1 ugb-button ugb-button--size-normal ugb-button--design-ghost" href="" rel=""><span class="ugb-button--inner">Button text</span></a></div></div></div></div>
<!-- /wp:ugb/button -->

<!-- wp:ugb/button {"button1Design":"ghost","button1Size":"medium","button1BackgroundColor":"#cd2653","button1BorderRadius":41,"button1BorderWidth":3,"uniqueClass":"ugb-90eacd1"} -->
<div class="wp-block-ugb-button ugb-button-wrapper ugb-90eacd1 ugb-main-block" id=""><style>.ugb-90eacd1 .ugb-button1 .ugb-button--inner{color:#cd2653}.ugb-90eacd1 .ugb-button1{border-color:#cd2653;border-width:3px;border-radius:41px !important}.ugb-90eacd1 .ugb-button1:hover .ugb-button--inner{color:#cd2653}.ugb-90eacd1 .ugb-button1:before{border-radius:41px !important}</style><div class="ugb-inner-block"><div class="ugb-block-content"><div class="ugb-button-container"><a class="ugb-button1 ugb-button ugb-button--size-medium ugb-button--design-ghost" href="" rel=""><span class="ugb-button--inner">Button text</span></a></div></div></div></div>
<!-- /wp:ugb/button -->
```

Result:
![Screen Shot 2020-02-20 at 12 19 43 AM](https://user-images.githubusercontent.com/1033611/74851813-b966f480-5376-11ea-86b4-094fa5e4c101.jpg)

This may affect other buttons of other blocks as well.

This should be addressed since native blocks are not affected by those styles
